version: '3.3'
services:
  accountapi:
    image: form3tech/interview-accountapi:latest
    restart: on-failure
    depends_on:
      - postgresql
      - vault
    ports:
      - 8080:8080
    environment: &env
      - FORM3_API=http://accountapi:8080
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=8fb95528-57c6-422e-9722-d2147bcba8ed
      - STACK_NAME=f3-interview-accountapi
      - PSQL_HOST=postgresql
      - PSQL_PORT=5432
      - PSQL_USER=root
      - PSQL_PASSWORD=password
      - DATABASE-HOST=postgresql
      - DATABASE-USERNAME=interview_accountapi_user
      - DATABASE-PASSWORD=123
      - DATABASE-SSL-MODE=disable

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - accountapi
    volumes:
      - ./:/app
    environment: *env

  postgresql:
    image: postgres:9.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10

  vault:
    image: vault:0.9.3
    ports:
      - 8200:8200
    environment:
      - SKIP_SETCAP=1
      - VAULT_DEV_ROOT_TOKEN_ID=8fb95528-57c6-422e-9722-d2147bcba8ed
